GET http://localhost:3000/

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "john",
    "password":"123456"
}

###
GET http://localhost:3000/Bye
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJwYXNzd29yZCI6IjEyMzQ1NiIsIm5hbWUiOiJKb2huIiwiZW1haWwiOiJqb2huQHN0dWRlbnQudXRlbS5lZHUubXkiLCJpYXQiOjE2ODEzNzE0NDUsImV4cCI6MTY4MTM3MTUwNX0.yg8ujd0eLJaYAv1SvZDagpnAD3nuvydnk2Vp-3EUZcw


###
Post http://localhost:3000/register
Content-Type: application/json

{
    "username": "utem",
    "password":"123456",
    "name":"utem",
    "email":"utem@m.com"
}